name: AIFES
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pre-commit==3.2.1
  - jupyterlab==3.6.2
  - openstef==3.2.59
  - fpdf==1.7.2
  - feather==0.1.2
  - kaleido==0.1.0.post1
  - ipynbname==2021.3.2
